name: yatir_viz
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - dask=2.9.1
  - distributed=2.9.1
  - geoviews=1.6.6
  - holoviews=1.12.7
  - hvplot=0.5.2
  - matplotlib=3.1.2
  - numpy=1.17.3
  - pandas=0.25.3
  - panel=0.7.0
  - seaborn=0.9.0
  - xarray=0.14.1
